// <auto-generated />
package PlainEnglish;

import java.util.LinkedList;
import java.util.Optional;

public class TokenManager
{
    private final LinkedList<Token> tokens;
    public TokenManager(LinkedList<Token> tokens)
    {
        this.tokens = tokens;
    }

    //return token that is dist away from current position
    public Optional<Token> peek(int dist) {
        return Optional.of(tokens.get(dist));
    }
    //if next token is of the type passed in, take it off of the list and return it
    //otherwise, dont remove it and return an empty optional
    public Optional<Token> matchAndRemove(Token.TokenTypes t) {
        //if at end just return an empty
        if(isAtEnd()) return Optional.empty();
        if(tokens.get(0).Type == t) {
            Token temp = tokens.get(0);
            tokens.pop();
            return Optional.of(temp);
        }
        return Optional.empty();
    }
    //check if no tokens left
    public boolean isAtEnd() {
        return tokens.isEmpty();
    }
    //return first tokens line numbwer
    //return -1 if cannot get line number
    public int getCurrentLine() {
        if(isAtEnd()) {
            return -1;
        }
        return tokens.get(0).LineNumber;
    }
    //return first tokens column number
    //return -1 if cannot get column number
    public int getCurrentColumnNumber() {
        if(isAtEnd()) {
            return -1;
        }
        return tokens.get(0).ColumnNumber;
    }
}

