// <auto-generated />
package PlainEnglish.AST;

import java.util.Optional;

public class BoolExpFactor
{
    public Optional<Expression> lhs = Optional.empty();
    public Optional<compareOps> thecompareOps = Optional.empty();
    public Optional<Expression> rhs = Optional.empty();
    public Optional<VariableReference> variablereference = Optional.empty();
}

