// <auto-generated />
package PlainEnglish.AST;

import java.util.Optional;

public class If
{
    public BoolExpTerm boolexpterm;
    public StatementBlock statementblock; 
    public boolean $else; 
    public Optional<StatementBlock> falseCase= Optional.empty();
}

