// <auto-generated />
package PlainEnglish.AST;

import java.util.Optional;

public class Parameter
{
    public String paramType; 
    public boolean named; 
    public Optional<String> nameOverride = Optional.empty();
}

