// <auto-generated />
package PlainEnglish.AST;

import java.util.Optional;

public class Statement
{
    public Optional<If> $if = Optional.empty();
    public Optional<Loop> loop = Optional.empty();
    public Optional<Set> set = Optional.empty();
    public Optional<Make> make = Optional.empty();
    public Optional<FunctionCall> functioncall = Optional.empty();
}

