import PlainEnglish.*;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.LinkedList;

public class Parser4Tests {

    @Test
    public void TestSimpleIf() throws Exception {
        var code = "To SimpleIf\n" +
                "    If 4 < 7\n" +
                "        Print with \"4\"\n" +
                "    If 'a' == 'A' or \"Hello\" != \"World\"\n" +
                "        Set boolVar to true\n" +
                "";
        var tokens = new LinkedList<Token>();
        tokens.add(new Token(Token.TokenTypes.TO,1,2));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,11,"SimpleIf"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,2,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,2,4));
        tokens.add(new Token(Token.TokenTypes.IF,2,6));
        tokens.add(new Token(Token.TokenTypes.NUMBER,2,8,"4"));
        tokens.add(new Token(Token.TokenTypes.LESSTHAN,2,10));
        tokens.add(new Token(Token.TokenTypes.NUMBER,2,12,"7"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,3,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,3,8));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,3,13,"Print"));
        tokens.add(new Token(Token.TokenTypes.WITH,3,18));
        tokens.add(new Token(Token.TokenTypes.STRINGLITERAL,3,22,"4"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,4,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,4,4));
        tokens.add(new Token(Token.TokenTypes.IF,4,6));
        tokens.add(new Token(Token.TokenTypes.CHARACTERLITERAL,4,7,"a"));
        tokens.add(new Token(Token.TokenTypes.DOUBLEEQUAL,4,10));
        tokens.add(new Token(Token.TokenTypes.CHARACTERLITERAL,4,11,"A"));
        tokens.add(new Token(Token.TokenTypes.OR,4,14));
        tokens.add(new Token(Token.TokenTypes.STRINGLITERAL,4,22,"Hello"));
        tokens.add(new Token(Token.TokenTypes.NOTEQUAL,4,25));
        tokens.add(new Token(Token.TokenTypes.STRINGLITERAL,4,33,"World"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,5,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,5,8));
        tokens.add(new Token(Token.TokenTypes.SET,5,11));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,5,19,"boolVar"));
        tokens.add(new Token(Token.TokenTypes.TO,5,22));
        tokens.add(new Token(Token.TokenTypes.TRUE,5,27));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,6,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,6,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,6,0));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,6,0));
        var ast = new PlainEnglishParser(tokens).program().orElseThrow();
        Assertions.assertEquals("SimpleIf",ast.method.get(0).name);
        Assertions.assertFalse(ast.method.get(0).with);
        Assertions.assertTrue(ast.method.get(0).className.isEmpty());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.not);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("4",ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).number.get());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("7",ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).number.get());
        Assertions.assertEquals(PlainEnglish.AST.compareOps.lessthan,ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().thecompareOps.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.isPresent());
        Assertions.assertEquals("Print",ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().obj.isEmpty());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("4",ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).stringliteral.get());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().$else);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(1).$if.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.not);
        Assertions.assertEquals("or",ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.theandORor.get(0).toString());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).not);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("Hello",ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).boolexpfactor.get().lhs.get().term.get(0).factor.get(0).stringliteral.get());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("World",ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).boolexpfactor.get().rhs.get().term.get(0).factor.get(0).stringliteral.get());
        Assertions.assertEquals(PlainEnglish.AST.compareOps.notequal,ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpterm.get(0).boolexpfactor.get().thecompareOps.get());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("a",ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).characterliteral.get());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("A",ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).characterliteral.get());
        Assertions.assertEquals(PlainEnglish.AST.compareOps.doubleequal,ast.method.get(0).statementblock.statement.get(1).$if.get().boolexpterm.boolexpfactor.get().thecompareOps.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(1).$if.get().statementblock.statement.get(0).set.isPresent());
        Assertions.assertEquals("boolVar",ast.method.get(0).statementblock.statement.get(1).$if.get().statementblock.statement.get(0).set.get().variablereference.name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(1).$if.get().statementblock.statement.get(0).set.get().variablereference.of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().statementblock.statement.get(0).set.get().variablereference.$object.isPresent());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(1).$if.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(0).$false);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).$if.get().$else);
    }

    @Test
    public void TestIfElse() throws Exception {
        var code = "To IfElse\n" +
                "    If numVar % 2 == 0\n" +
                "        Print with \"Even\"\n" +
                "    Else\n" +
                "        Print with \"Odd\"\n" +
                "";

        var tokens = new LinkedList<Token>();
        tokens.add(new Token(Token.TokenTypes.TO,1,2));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,9,"IfElse"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,2,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,2,4));
        tokens.add(new Token(Token.TokenTypes.IF,2,6));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,2,13,"numVar"));
        tokens.add(new Token(Token.TokenTypes.PERCENT,2,15));
        tokens.add(new Token(Token.TokenTypes.NUMBER,2,17,"2"));
        tokens.add(new Token(Token.TokenTypes.DOUBLEEQUAL,2,20));
        tokens.add(new Token(Token.TokenTypes.NUMBER,2,22,"0"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,3,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,3,8));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,3,13,"Print"));
        tokens.add(new Token(Token.TokenTypes.WITH,3,18));
        tokens.add(new Token(Token.TokenTypes.STRINGLITERAL,3,25,"Even"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,4,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,4,4));
        tokens.add(new Token(Token.TokenTypes.ELSE,4,8));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,5,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,5,8));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,5,13,"Print"));
        tokens.add(new Token(Token.TokenTypes.WITH,5,18));
        tokens.add(new Token(Token.TokenTypes.STRINGLITERAL,5,24,"Odd"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,6,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,6,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,6,0));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,6,0));
        var ast = new PlainEnglishParser(tokens).program().orElseThrow();
        Assertions.assertEquals("IfElse",ast.method.get(0).name);
        Assertions.assertFalse(ast.method.get(0).with);
        Assertions.assertTrue(ast.method.get(0).className.isEmpty());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.not);
        Assertions.assertEquals(PlainEnglish.AST.asteriskORslashORpercent.percent,ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).theasteriskORslashORpercent.get(0));
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("numVar",ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(1).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(1).$false);
        Assertions.assertEquals("2",ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(1).number.get());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("0",ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).number.get());
        Assertions.assertEquals(PlainEnglish.AST.compareOps.doubleequal,ast.method.get(0).statementblock.statement.get(0).$if.get().boolexpterm.boolexpfactor.get().thecompareOps.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.isPresent());
        Assertions.assertEquals("Print",ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().obj.isEmpty());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("Even",ast.method.get(0).statementblock.statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).stringliteral.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.get().$else);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.isPresent());
        Assertions.assertEquals("Print",ast.method.get(0).statementblock.statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().obj.isEmpty());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("Odd",ast.method.get(0).statementblock.statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).stringliteral.get());
    }

    @Test
    public void TestLoop() throws Exception {
        var code = "To Exponent with number, number named val\n" +
                "    Make number named i\n" +
                "    Set i to 1\n" +
                "    Loop i <= number\n" +
                "        Set val to val * val\n" +
                "";
        var tokens = new LinkedList<Token>();
        tokens.add(new Token(Token.TokenTypes.TO,1,2));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,11,"Exponent"));
        tokens.add(new Token(Token.TokenTypes.WITH,1,16));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,23,"number"));
        tokens.add(new Token(Token.TokenTypes.COMMA,1,24));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,31,"number"));
        tokens.add(new Token(Token.TokenTypes.NAMED,1,37));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,41,"val"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,2,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,2,4));
        tokens.add(new Token(Token.TokenTypes.MAKE,2,8));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,2,15,"number"));
        tokens.add(new Token(Token.TokenTypes.NAMED,2,21));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,2,23,"i"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,3,0));
        tokens.add(new Token(Token.TokenTypes.SET,3,7));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,3,9,"i"));
        tokens.add(new Token(Token.TokenTypes.TO,3,12));
        tokens.add(new Token(Token.TokenTypes.NUMBER,3,14,"1"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,4,0));
        tokens.add(new Token(Token.TokenTypes.LOOP,4,8));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,4,10,"i"));
        tokens.add(new Token(Token.TokenTypes.LESSTHANEQUAL,4,13));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,4,20,"number"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,5,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,5,8));
        tokens.add(new Token(Token.TokenTypes.SET,5,11));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,5,15,"val"));
        tokens.add(new Token(Token.TokenTypes.TO,5,18));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,5,22,"val"));
        tokens.add(new Token(Token.TokenTypes.ASTERISK,5,24));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,5,28,"val"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,6,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,6,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,6,0));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,6,0));
        var ast = new PlainEnglishParser(tokens).program().orElseThrow();
        Assertions.assertEquals("Exponent",ast.method.get(0).name);
        Assertions.assertTrue(ast.method.get(0).with);
        Assertions.assertTrue(ast.method.get(0).className.isEmpty());
        Assertions.assertEquals("number",ast.method.get(0).parameter.get(0).paramType);
        Assertions.assertFalse(ast.method.get(0).parameter.get(0).named);
        Assertions.assertEquals("number",ast.method.get(0).parameter.get(1).paramType);
        Assertions.assertTrue(ast.method.get(0).parameter.get(1).named);
        Assertions.assertEquals("val",ast.method.get(0).parameter.get(1).nameOverride.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).make.isPresent());
        Assertions.assertEquals("number",ast.method.get(0).statementblock.statement.get(0).make.get().type);
        Assertions.assertEquals("i",ast.method.get(0).statementblock.statement.get(0).make.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(1).set.isPresent());
        Assertions.assertEquals("i",ast.method.get(0).statementblock.statement.get(1).set.get().variablereference.name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(1).set.get().variablereference.of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().variablereference.$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).$false);
        Assertions.assertEquals("1",ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).number.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).loop.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.not);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("i",ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("number",ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.compareOps.lessthanequal,ast.method.get(0).statementblock.statement.get(2).loop.get().boolexpterm.boolexpfactor.get().thecompareOps.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.isPresent());
        Assertions.assertEquals("val",ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().variablereference.name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().variablereference.of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().variablereference.$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.asteriskORslashORpercent.asterisk,ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).theasteriskORslashORpercent.get(0));
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(0).$false);
        Assertions.assertEquals("val",ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(1).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(1).$false);
        Assertions.assertEquals("val",ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(1).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(1).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).loop.get().statementblock.statement.get(0).set.get().expression.term.get(0).factor.get(1).variablereference.get().$object.isPresent());
    }

    @Test
    public void TestFunctionCall() throws Exception {
        var code = "To Search with number named start, number named end, number named value, number named searchCalls\n" +
                "    Make number named current\n" +
                "    Set current to start + (end - start)/2\n" +
                "    If current == value\n" +
                "        Print with \"Found after \", searchCalls\n" +
                "    Else\n" +
                "        If current < value\n" +
                "            Search with current, end, value, searchCalls + 1\n" +
                "        Else\n" +
                "            Search with start, current, value, searchCalls + 1\n" +
                "\n" +
                "To Run\n" +
                "    Search with 0, 25, 10, 1\n" +
                "";

        var tokens = new LinkedList<Token>();
        tokens.add(new Token(Token.TokenTypes.TO,1,2));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,9,"Search"));
        tokens.add(new Token(Token.TokenTypes.WITH,1,14));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,21,"number"));
        tokens.add(new Token(Token.TokenTypes.NAMED,1,27));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,33,"start"));
        tokens.add(new Token(Token.TokenTypes.COMMA,1,34));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,41,"number"));
        tokens.add(new Token(Token.TokenTypes.NAMED,1,47));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,51,"end"));
        tokens.add(new Token(Token.TokenTypes.COMMA,1,52));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,59,"number"));
        tokens.add(new Token(Token.TokenTypes.NAMED,1,65));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,71,"value"));
        tokens.add(new Token(Token.TokenTypes.COMMA,1,72));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,79,"number"));
        tokens.add(new Token(Token.TokenTypes.NAMED,1,85));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,1,97,"searchCalls"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,2,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,2,4));
        tokens.add(new Token(Token.TokenTypes.MAKE,2,8));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,2,15,"number"));
        tokens.add(new Token(Token.TokenTypes.NAMED,2,21));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,2,29,"current"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,3,0));
        tokens.add(new Token(Token.TokenTypes.SET,3,7));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,3,15,"current"));
        tokens.add(new Token(Token.TokenTypes.TO,3,18));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,3,24,"start"));
        tokens.add(new Token(Token.TokenTypes.PLUS,3,26));
        tokens.add(new Token(Token.TokenTypes.OPENPAREN,3,28));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,3,31,"end"));
        tokens.add(new Token(Token.TokenTypes.HYPHEN,3,33));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,3,39,"start"));
        tokens.add(new Token(Token.TokenTypes.CLOSEPAREN,3,40));
        tokens.add(new Token(Token.TokenTypes.SLASH,3,41));
        tokens.add(new Token(Token.TokenTypes.NUMBER,3,42,"2"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,4,0));
        tokens.add(new Token(Token.TokenTypes.IF,4,6));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,4,14,"current"));
        tokens.add(new Token(Token.TokenTypes.DOUBLEEQUAL,4,17));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,4,23,"value"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,5,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,5,8));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,5,13,"Print"));
        tokens.add(new Token(Token.TokenTypes.WITH,5,18));
        tokens.add(new Token(Token.TokenTypes.STRINGLITERAL,5,33,"Found after "));
        tokens.add(new Token(Token.TokenTypes.COMMA,5,34));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,5,46,"searchCalls"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,6,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,6,4));
        tokens.add(new Token(Token.TokenTypes.ELSE,6,8));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,7,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,7,8));
        tokens.add(new Token(Token.TokenTypes.IF,7,10));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,7,18,"current"));
        tokens.add(new Token(Token.TokenTypes.LESSTHAN,7,20));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,7,26,"value"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,8,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,8,12));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,8,18,"Search"));
        tokens.add(new Token(Token.TokenTypes.WITH,8,23));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,8,31,"current"));
        tokens.add(new Token(Token.TokenTypes.COMMA,8,32));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,8,36,"end"));
        tokens.add(new Token(Token.TokenTypes.COMMA,8,37));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,8,43,"value"));
        tokens.add(new Token(Token.TokenTypes.COMMA,8,44));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,8,56,"searchCalls"));
        tokens.add(new Token(Token.TokenTypes.PLUS,8,58));
        tokens.add(new Token(Token.TokenTypes.NUMBER,8,60,"1"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,9,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,9,8));
        tokens.add(new Token(Token.TokenTypes.ELSE,9,12));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,10,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,10,12));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,10,18,"Search"));
        tokens.add(new Token(Token.TokenTypes.WITH,10,23));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,10,29,"start"));
        tokens.add(new Token(Token.TokenTypes.COMMA,10,30));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,10,38,"current"));
        tokens.add(new Token(Token.TokenTypes.COMMA,10,39));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,10,45,"value"));
        tokens.add(new Token(Token.TokenTypes.COMMA,10,46));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,10,58,"searchCalls"));
        tokens.add(new Token(Token.TokenTypes.PLUS,10,60));
        tokens.add(new Token(Token.TokenTypes.NUMBER,10,62,"1"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,11,0));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,12,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,12,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,12,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,12,0));
        tokens.add(new Token(Token.TokenTypes.TO,12,2));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,12,6,"Run"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,13,0));
        tokens.add(new Token(Token.TokenTypes.INDENT,13,4));
        tokens.add(new Token(Token.TokenTypes.IDENTIFIER,13,10,"Search"));
        tokens.add(new Token(Token.TokenTypes.WITH,13,15));
        tokens.add(new Token(Token.TokenTypes.NUMBER,13,17,"0"));
        tokens.add(new Token(Token.TokenTypes.COMMA,13,18));
        tokens.add(new Token(Token.TokenTypes.NUMBER,13,21,"25"));
        tokens.add(new Token(Token.TokenTypes.COMMA,13,22));
        tokens.add(new Token(Token.TokenTypes.NUMBER,13,25,"10"));
        tokens.add(new Token(Token.TokenTypes.COMMA,13,26));
        tokens.add(new Token(Token.TokenTypes.NUMBER,13,28,"1"));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,14,0));
        tokens.add(new Token(Token.TokenTypes.DEDENT,14,0));
        tokens.add(new Token(Token.TokenTypes.NEWLINE,14,0));
        var ast = new PlainEnglishParser(tokens).program().orElseThrow();
        Assertions.assertEquals("Search",ast.method.get(0).name);
        Assertions.assertTrue(ast.method.get(0).with);
        Assertions.assertTrue(ast.method.get(0).className.isEmpty());
        Assertions.assertEquals("number",ast.method.get(0).parameter.get(0).paramType);
        Assertions.assertTrue(ast.method.get(0).parameter.get(0).named);
        Assertions.assertEquals("start",ast.method.get(0).parameter.get(0).nameOverride.get());
        Assertions.assertEquals("number",ast.method.get(0).parameter.get(1).paramType);
        Assertions.assertTrue(ast.method.get(0).parameter.get(1).named);
        Assertions.assertEquals("end",ast.method.get(0).parameter.get(1).nameOverride.get());
        Assertions.assertEquals("number",ast.method.get(0).parameter.get(2).paramType);
        Assertions.assertTrue(ast.method.get(0).parameter.get(2).named);
        Assertions.assertEquals("value",ast.method.get(0).parameter.get(2).nameOverride.get());
        Assertions.assertEquals("number",ast.method.get(0).parameter.get(3).paramType);
        Assertions.assertTrue(ast.method.get(0).parameter.get(3).named);
        Assertions.assertEquals("searchCalls",ast.method.get(0).parameter.get(3).nameOverride.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(0).make.isPresent());
        Assertions.assertEquals("number",ast.method.get(0).statementblock.statement.get(0).make.get().type);
        Assertions.assertEquals("current",ast.method.get(0).statementblock.statement.get(0).make.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(1).set.isPresent());
        Assertions.assertEquals("current",ast.method.get(0).statementblock.statement.get(1).set.get().variablereference.name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(1).set.get().variablereference.of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().variablereference.$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.plusORhyphen.plus,ast.method.get(0).statementblock.statement.get(1).set.get().expression.theplusORhyphen.get(0));
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).$false);
        Assertions.assertEquals("start",ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.asteriskORslashORpercent.slash,ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).theasteriskORslashORpercent.get(0));
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).$false);
        Assertions.assertEquals(PlainEnglish.AST.plusORhyphen.hyphen,ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().theplusORhyphen.get(0));
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("end",ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(1).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(1).factor.get(0).$false);
        Assertions.assertEquals("start",ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(1).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(1).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(0).expression.get().term.get(1).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(1).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(1).$false);
        Assertions.assertEquals("2",ast.method.get(0).statementblock.statement.get(1).set.get().expression.term.get(1).factor.get(1).number.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.not);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("current",ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("value",ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.compareOps.doubleequal,ast.method.get(0).statementblock.statement.get(2).$if.get().boolexpterm.boolexpfactor.get().thecompareOps.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.isPresent());
        Assertions.assertEquals("Print",ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().obj.isEmpty());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("Found after ",ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).stringliteral.get());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("searchCalls",ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().$else);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.not);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("current",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().lhs.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).$false);
        Assertions.assertEquals("value",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().rhs.get().term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.compareOps.lessthan,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().boolexpterm.boolexpfactor.get().thecompareOps.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.isPresent());
        Assertions.assertEquals("Search",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().obj.isEmpty());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("current",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("end",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("value",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.plusORhyphen.plus,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).theplusORhyphen.get(0));
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("searchCalls",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(1).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(1).factor.get(0).$false);
        Assertions.assertEquals("1",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(1).factor.get(0).number.get());
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().$else);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.isPresent());
        Assertions.assertEquals("Search",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().name);
        Assertions.assertTrue(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().obj.isEmpty());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("start",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("current",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("value",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertEquals(PlainEnglish.AST.plusORhyphen.plus,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).theplusORhyphen.get(0));
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("searchCalls",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).variablereference.get().name);
        Assertions.assertEquals(false,ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).variablereference.get().of);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).variablereference.get().$object.isPresent());
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(1).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(1).factor.get(0).$false);
        Assertions.assertEquals("1",ast.method.get(0).statementblock.statement.get(2).$if.get().falseCase.get().statement.get(0).$if.get().falseCase.get().statement.get(0).functioncall.get().parameter.get(3).term.get(1).factor.get(0).number.get());
        Assertions.assertEquals("Run",ast.method.get(1).name);
        Assertions.assertFalse(ast.method.get(1).with);
        Assertions.assertTrue(ast.method.get(1).className.isEmpty());
        Assertions.assertTrue(ast.method.get(1).statementblock.statement.get(0).functioncall.isPresent());
        Assertions.assertEquals("Search",ast.method.get(1).statementblock.statement.get(0).functioncall.get().name);
        Assertions.assertTrue(ast.method.get(1).statementblock.statement.get(0).functioncall.get().obj.isEmpty());
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("0",ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(0).term.get(0).factor.get(0).number.get());
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("25",ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(1).term.get(0).factor.get(0).number.get());
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("10",ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(2).term.get(0).factor.get(0).number.get());
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).$true);
        Assertions.assertFalse(ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).$false);
        Assertions.assertEquals("1",ast.method.get(1).statementblock.statement.get(0).functioncall.get().parameter.get(3).term.get(0).factor.get(0).number.get());
    }
}
