// <auto-generated />
package PlainEnglish.AST;

import java.util.LinkedList;

public class Program
{
    public LinkedList<TypeDef> typedef = new LinkedList<>();
    public LinkedList<Method> method = new LinkedList<>();
}

