// <auto-generated />
package PlainEnglish;

import java.util.LinkedList;
import java.util.Optional;

public class TokenManager
{
    private final LinkedList<Token> tokens;
    public TokenManager(LinkedList<Token> tokens)
    {
        this.tokens = tokens;
    }

}

