// <auto-generated />
package PlainEnglish.AST;

import java.util.LinkedList;
import java.util.Optional;

public class BoolExpTerm
{
    public Optional<BoolExpFactor> boolexpfactor = Optional.empty();
    public LinkedList<andORor> theandORor = new LinkedList<>();
    public LinkedList<BoolExpTerm> boolexpterm = new LinkedList<>();
    public boolean not; 
    public Optional<BoolExpTerm> notTerm = Optional.empty();
}

