// <auto-generated />
package PlainEnglish.AST;

import java.util.LinkedList;

public class Expression
{
    public LinkedList<Term> term= new LinkedList<>();
    public LinkedList<plusORhyphen> theplusORhyphen= new LinkedList<>();
}

