// <auto-generated />
package PlainEnglish.AST;

import java.util.Optional;

public class Factor
{
    public Optional<String> number = Optional.empty();
    public Optional<VariableReference> variablereference= Optional.empty();
    public boolean $true; 
    public boolean $false; 
    public Optional<String> stringliteral= Optional.empty();
    public Optional<String> characterliteral= Optional.empty();
    public Optional<Expression> expression= Optional.empty();
}

