// <auto-generated />
package PlainEnglish.AST;

import java.util.LinkedList;
import java.util.Optional;

public class FunctionCall
{
    public String name;
    public Optional<String> obj= Optional.empty();
    public LinkedList<Expression> parameter= new LinkedList<>();
}

