// <auto-generated />
package PlainEnglish.AST;

import java.util.LinkedList;
import java.util.Optional;

public class Method
{
    public String name; 
    public Optional<String> className = Optional.empty();
    public boolean with; 
    public LinkedList<Parameter> parameter = new LinkedList<>();
    public StatementBlock statementblock; 
}

