// <auto-generated />
package PlainEnglish.AST;

import java.util.LinkedList;

public class Term
{
    public LinkedList<Factor> factor = new LinkedList<>();
    public LinkedList<asteriskORslashORpercent> theasteriskORslashORpercent = new LinkedList<>();
}

