// <auto-generated />
package PlainEnglish.AST;

import java.util.Optional;

public class VariableReference
{
    public String name; 
    public boolean of; 
    public Optional<String> $object = Optional.empty();
}

